### ISSUE TITLE
`ScrollSnake.gif`

### ISSUE THREAD

**Issue by chrisscholly** [ZevEisenberg/ScrollSnake#1]
Hi @ZevEisenberg 
First of all, nice work! 👍  🎉
Could pls let me know which kind of tool do you used to create `ScrollSnake.gif`? Has a pretty good quality 👌
Thanks in advance :)

**Comment by ZevEisenberg** [comment]
Hey, @chrisscholly! I'm so glad you asked :)
A little while ago, I threw together this shell function, which uses ffmpeg to generate GIFs. I then drop the GIF into [ImageOptim](https://imageoptim.com/mac), which drops the file size a bit further. Here's the script:

```sh
function movToGif
{
    local function printUsage()
    {
        echo "Usage: movToGif path/to/movie.mov path/to/output.gif [border]"
        echo "(If you specify \"border\" as the last parameter,"
        echo "a thin black border will be drawn."
    }

    if [[ $# == 0 ]]; then
        printUsage
        return
    fi

    palette=`mktemp -d`"/palette.png"

    # deletes the temp palette
    function cleanup {
        rm "$palette"
        echo "deleted palette at $palette"
    }

    trap cleanup EXIT

    border=""
    if [[ $3 == "border" ]]; then
        border=",pad=iw+4:ih+4:2:2"
    fi

    filters="fps=15,setpts=0.8*PTS$border,scale=320:-1:flags=lanczos"

    ffmpeg -v warning -i "$1" -vf "$filters,palettegen" -y $palette
    ffmpeg -v warning -i "$1" -i $palette -lavfi "$filters [x]; [x][1:v] paletteuse" -y "$2"
}
```

It's based on [this work](https://github.com/Raizlabs/RIGImageGallery/wiki/Animated-GIF-Creation) by @atelierclockwork, plus some tweaks that I added. I did some experimentation and settled on `fps=15` and `scale=320` (320 px on longest side), but you can tweak them for your needs.

**Comment by chrisscholly** [comment]
Very cool stuff @ZevEisenberg 👍 
Thank you a lot 🙌
